-- 스터디 참여자 조회
SELECT 
       A.ID         AS STUDY_MEMBER_ID
     , B.NICKNAME   AS STUDY_MEMBER_NICKNAME
     , C.NAME       AS STUDY_MEMBER_RANK
     , A.ROLE       AS STUDY_MEMBER_ROLE
  FROM STUDY_MEMBER A
  JOIN MEMBER B      ON A.MEMBER_ID = B.ID
  JOIN MEMBER_RANK C ON B.RANK_ID   = C.ID
 WHERE A.STUDY_ID = 1 --  #{studyId}        
ORDER BY 
    CASE WHEN A.ROLE = 'LEADER' 
	      THEN 0 ELSE 1 END,
    B.NICKNAME ASC;
    
    
-- 스터디 게시물 전체 조회
SELECT 
       A.ID         AS POST_ID
     , C.NICKNAME   AS AUTHOR_NICKNAME
     , A.TITLE      AS TITLE
     , A.CREATED_AT AS CREATED_AT
  FROM STUDY_POST A
  JOIN STUDY_MEMBER B ON A.MEMBER_ID = B.ID
  JOIN MEMBER C       ON B.MEMBER_ID = C.ID
 WHERE A.STUDY_ID = 1        -- #{studyId}
   AND A.VISIBILITY = 'Y'
ORDER BY A.CREATED_AT DESC;

-- 스터디 게시물 상세 조회
SELECT 
       A.ID         AS POST_ID
     , C.NICKNAME   AS AUTHOR_NICKNAME
     , D.NAME       AS AUTHOR_RANK
     , A.TITLE      AS TITLE  
     , A.CREATED_AT AS CREATED_AT
     , A.UPDATED_AT AS UPDATED_AT
     , A.CONTENT    AS CONTENT 
     , E.IMAGE_URL  AS IMAGE
  FROM STUDY_POST A
  JOIN STUDY_MEMBER B ON A.MEMBER_ID = B.ID
  JOIN MEMBER C       ON B.MEMBER_ID = C.ID
  JOIN MEMBER_RANK D  ON C.RANK_ID   = D.ID
  LEFT JOIN STUDY_POST_IMAGE E ON A.ID = E.POST_ID
 WHERE A.ID = 7              -- #{postId}
   AND A.VISIBILITY = 'Y';

-- 스터디 게시물 댓글 조회
SELECT 
       A.POST_ID     AS POST_ID
     , C.NICKNAME    AS AUTHOR_NICKNAME
     , D.NAME        AS AUTHOR_RANK
     , A.CONTENT     AS CONTENT
     , A.CREATED_AT  AS CREATED_AT 
     , A.UPDATED_AT  AS UPDATED_AT
  FROM STUDY_COMMENT A
  JOIN STUDY_MEMBER B ON A.MEMBER_ID = B.ID
  JOIN MEMBER C       ON B.MEMBER_ID = C.ID
  JOIN MEMBER_RANK D  ON C.RANK_ID   = D.ID
 WHERE A.POST_ID = 2    -- #{postId}
   AND A.VISIBILITY = 'Y'
ORDER BY A.CREATED_AT ASC;


-- 게시물 로드맵 전체 조회
SELECT 
       A.STUDY_ID  AS STUDY_ID
     , A.TITLE     AS ROADMAP_TITLE
  FROM STUDY_ROADMAP A
 WHERE A.STUDY_ID = 1   -- #{studyId}
ORDER BY A.`ORDER`;


-- 게시물 로드맵 상세 조회
SELECT 
       A.ID          AS ROADMAP_ID
     , A.TITLE       AS ROADMAP_TITLE
     , A.DESCRIPTION AS ROADMAP_DESCRIPTION
     , B.TITLE       AS MILESTONE_TITLE
  FROM STUDY_ROADMAP A
  LEFT JOIN STUDY_MILESTONE B ON A.ID = B.ROADMAP_ID
 WHERE A.ID = 1      -- #{roadmapId}
ORDER BY B.`ORDER`;


-- 로드맵 마일스톤 상세 조회
SELECT 
       A.ID          AS MILESTONE_ID
     , A.TITLE       AS MILESTONE_TITLE
     , A.DESCRIPTION AS MILESTONE_DESCRIPTION
  FROM STUDY_MILESTONE A
 WHERE A.ID = 2;   -- #{milestoneId}
