-- 회원
-- 스터디 모집 게시물 전체 목록 조회 기능

SELECT 
       A.ID AS POST_ID
     , B.ID AS MEMBER_ID
     , B.NICKNAME AS MEMBER_NICKNAME
     , A.TITLE AS POST_TITLE
     , A.START_DATE AS START_DATE
     , A.END_DATE AS END_DATE
     , A.EXPIRES_AT AS EXPIRES_AT
     , A.STATUS AS STATUS
     , A.CAPACITY AS CAPACITY
     , COUNT(D.ID) AS PARTICIPANT_COUNT -- 참여자 수 계산
     , A.COMMENT_COUNT AS COMMENT_COUNT
     , A.CREATED_AT AS CREATED_AT
     , A.UPDATED_AT AS UPDATED_AT
     , A.VISIBILITY AS VISIBILITY
     , C.NAME AS RANK_NAME
  FROM STUDY_RECRUIT_POST A
  JOIN MEMBER B ON A.MEMBER_ID = B.ID
  JOIN MEMBER_RANK C ON B.RANK_ID = C.ID
  LEFT JOIN STUDY_RECRUIT_MEMBER D ON A.ID = D.POST_ID AND D.STATUS = 'APPROVED'
 WHERE VISIBILITY = 'Y'
 GROUP BY A.ID
 ORDER BY A.ID DESC;

-- --------------------------------------------------------------------------------------------------------
-- 스터디 모집 게시물 목록 모집 중인 글만 조회 기능

SELECT 
       A.ID AS POST_ID
     , B.ID AS MEMBER_ID
     , B.NICKNAME AS MEMBER_NICKNAME
     , A.TITLE AS POST_TITLE
     , A.START_DATE AS START_DATE
     , A.END_DATE AS END_DATE
     , A.EXPIRES_AT AS EXPIRES_AT
     , A.STATUS AS STATUS
     , A.CAPACITY AS CAPACITY
     , COUNT(D.ID) AS PARTICIPANT_COUNT -- 참여자 수 계산
     , A.COMMENT_COUNT AS COMMENT_COUNT
     , A.CREATED_AT AS CREATED_AT
     , A.UPDATED_AT AS UPDATED_AT
     , A.VISIBILITY AS VISIBILITY
     , C.NAME AS RANK_NAME
  FROM STUDY_RECRUIT_POST A
  JOIN MEMBER B ON A.MEMBER_ID = B.ID
  JOIN MEMBER_RANK C ON B.RANK_ID = C.ID
  LEFT JOIN STUDY_RECRUIT_MEMBER D ON A.ID = D.POST_ID AND D.STATUS = 'APPROVED'
 WHERE A.STATUS = 'OPEN' AND VISIBILITY = 'Y'
 GROUP BY A.ID
 ORDER BY A.ID DESC;

-- --------------------------------------------------------------------------------------------------------------------------------------
-- 스터디모집 게시물 상세 조회 기능

SELECT 
       A.ID AS POST_ID
     , B.ID AS MEMBER_ID
     , B.NICKNAME AS MEMBER_NICKNAME
     , A.TITLE AS POST_TITLE
     , A.CONTENT AS POST_CONTENT
     , A.START_DATE
     , A.END_DATE
     , A.EXPIRES_AT
     , A.STATUS AS STATUS
     , A.CAPACITY
     , COUNT(B.ID) AS PARTICIPANT_COUNT -- 참여자 수 계산
     , A.COMMENT_COUNT
     , A.CREATED_AT
     , A.UPDATED_AT
     , A.VISIBILITY
  FROM STUDY_RECRUIT_POST A
  JOIN MEMBER B ON A.MEMBER_ID = B.ID
  LEFT JOIN STUDY_RECRUIT_MEMBER C ON A.ID = C.POST_ID AND C.STATUS = 'APPROVED' -- 승인된 신청자만 세기
 WHERE A.ID = 11 AND VISIBILITY = 'Y'-- 특정 게시물 ID로 필터링 #{postId}
 GROUP BY A.ID;

    
-- -------------------------------------------------------------------------------------------------------------------
-- 스터디댓글 조회 기능

SELECT 
       A.ID AS COMMENT_ID
     , A.PARENT_ID AS PARENT_ID
     , B.ID AS MEMBER_ID
     , B.NICKNAME AS COMMENTER_NICKNAME
     , C.NAME AS MEMBER_RANK
     , A.CONTENT AS COMMENT_CONTENT
     , A.CREATED_AT AS CREATED_AT
     , A.UPDATED_AT AS UPDATED_AT
     , A.POST_ID AS POST_ID
     , A.VISIBILITY AS COMMENT_VISIBILITY
  FROM STUDY_COMMENT A JOIN MEMBER B ON A.MEMBER_ID = B.ID
  JOIN MEMBER_RANK C ON B.RANK_ID = C.ID  	-- 회원 등급 테이블 조인
 WHERE A.POST_ID = 1 AND VISIBILITY = 'Y'
 ORDER BY CASE WHEN A.PARENT_ID IS NULL THEN A.ID
               ELSE A.PARENT_ID END ASC,
                    A.ID ASC; 								

    
-- -----------------------------------------------------------------------------------------------------------------
-- 스터디 모집 신청 리스트 조회 기능(스터디장만 조회가능)	

SELECT 
       A.ID AS RECRUIT_MEMBER_ID
     , B.ID AS MEMBER_ID
     , B.NICKNAME AS NICKNAME
     , D.NAME AS MEMBER_RANK
     , B.EMAIL AS MEMBER_EMAIL
     , C.ID AS POST_ID
     , C.TITLE AS POST_TITLE
     , A.STATUS AS RECRUIT_MEMBER_STATUS
     , C.MEMBER_ID AS STUDY_LEADER
  FROM STUDY_RECRUIT_MEMBER A
  JOIN MEMBER B ON A.MEMBER_ID = B.ID
  JOIN STUDY_RECRUIT_POST C ON A.POST_ID = C.ID
  JOIN MEMBER_RANK D ON B.RANK_ID = D.ID
 WHERE C.ID = 1 AND C.MEMBER_ID		-- 해당 게시물의 작성자만 조회 가능
 ORDER BY C.START_DATE ASC;

-- ---------------------------------------------------------------------------
-- 관리자
-- 스터디 모집 게시물 전체 목록 조회 기능(VISIBILITY 조건 무시)
SELECT 
       A.ID AS POST_ID
     , B.ID AS MEMBER_ID
     , B.NICKNAME AS MEMBER_NICKNAME
     , A.TITLE AS POST_TITLE
     , A.START_DATE AS START_DATE
     , A.END_DATE AS END_DATE
     , A.EXPIRES_AT AS EXPIRES_AT
     , A.STATUS AS STATUS
     , A.CAPACITY AS CAPACITY
     , COUNT(D.ID) AS PARTICIPANT_COUNT -- 참여자 수 계산
     , A.COMMENT_COUNT AS COMMENT_COUNT
     , A.CREATED_AT AS CREATED_AT
     , A.UPDATED_AT AS UPDATED_AT
     , A.VISIBILITY AS VISIBILITY
     , C.NAME AS RANK_NAME
  FROM STUDY_RECRUIT_POST A
  JOIN MEMBER B ON A.MEMBER_ID = B.ID
  JOIN MEMBER_RANK C ON B.RANK_ID = C.ID
  LEFT JOIN STUDY_RECRUIT_MEMBER D ON A.ID = D.POST_ID AND D.STATUS = 'APPROVED'
 GROUP BY A.ID
 ORDER BY A.ID ASC;

-- -------------------------------------------------------------------------------------------------
-- 스터디모집 게시물 상세 조회 기능(VISIBILITY 조건 무시)

SELECT 
       A.ID AS POST_ID
     , B.ID AS MEMBER_ID
     , B.NICKNAME AS MEMBER_NICKNAME
     , A.TITLE AS POST_TITLE
     , A.CONTENT AS POST_CONTENT
     , A.START_DATE
     , A.END_DATE
     , A.EXPIRES_AT
     , A.STATUS AS STATUS
     , A.CAPACITY
     , COUNT(B.ID) AS PARTICIPANT_COUNT -- 참여자 수 계산
     , A.COMMENT_COUNT
     , A.CREATED_AT
     , A.UPDATED_AT
     , A.VISIBILITY
  FROM STUDY_RECRUIT_POST A
  JOIN MEMBER B ON A.MEMBER_ID = B.ID
  LEFT JOIN STUDY_RECRUIT_MEMBER C ON A.ID = C.POST_ID AND C.STATUS = 'APPROVED' -- 승인된 신청자만 세기
 WHERE A.ID = 11 -- 특정 게시물 ID로 필터링 #{postId}
 GROUP BY A.ID; 
-- -------------------------------------------------------------------------------------------------------------------
-- 스터디댓글 조회 기능(VISIBILITY 조건 무시)

SELECT 
       A.ID AS COMMENT_ID
     , A.PARENT_ID AS PARENT_ID
     , B.ID AS MEMBER_ID
     , B.NICKNAME AS COMMENTER_NICKNAME
     , C.NAME AS MEMBER_RANK
     , A.CONTENT AS COMMENT_CONTENT
     , A.CREATED_AT AS CREATED_AT
     , A.UPDATED_AT AS UPDATED_AT
     , A.POST_ID AS POST_ID
     , A.VISIBILITY AS COMMENT_VISIBILITY
  FROM STUDY_COMMENT A JOIN MEMBER B ON A.MEMBER_ID = B.ID
  JOIN MEMBER_RANK C ON B.RANK_ID = C.ID  	-- 회원 등급 테이블 조인
 WHERE A.POST_ID = 1
 ORDER BY CASE WHEN A.PARENT_ID IS NULL THEN A.ID
               ELSE A.PARENT_ID END ASC,
                    A.ID ASC; 
